### ISSUE TITLE
Logged in user lost in refresh

### ISSUE THREAD

**Issue by mauquoic** [MGrin/thau#44]
When the user (or his id) is needed on a page, and the page is refreshed, the application errors with a message TypeError: Cannot read property 'id' of undefined.

The relevant console output seems to be the following:
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in AuthProvider (at App.tsx:21)
    in ThemeProvider (at App.tsx:19)
    in App (at src/index.tsx:9)

**Comment by MGrin** [comment]
@mauquoic when you use `useUser` be ready to the fact that `user` can be undefined. Basically it is on every startup, while react-thau exchanges the token agains the user object.

To know the status of the thau startup you have the `useAuth` hook that will expose you loading, error and some other fields. This hook should be used alongside with `useUser` to ease you the check of the status

**Comment by mauquoic** [comment]
So what I had now as a workaround was:
  useEffect(() => {
    if (user) {
      AccountService....
      }
  }, [user, accountId]);

You're saying the correct, thau way is actually to do:
  useEffect(() => {
    if (!auth.loading) {
      AccountService...
    }
  }, [auth, accountId]);

**Comment by MGrin** [comment]
TBH the usual React way of working with such libs is kinda the following:
1. You wrap your app with the Provider
2. Somewhere on top of your tree, close to the provider, you have a component that looks like that:
```tsx
const { loading: authLoading, error: authError } = useAuth()
if (authLoading) {
    return <LoadingComponent />
}

if (authError) {
    // Something went wrong with the Thau initialization , probably your backend is not working
    // So in this case your app can not handle auth at all
    // You decide what to do, but usually you show something like "Sorry, we have some issues"
    return <p>Error: {authError.message}</p>
}

return <You application>
```
3. And then where you want to use the user, you can simply
```tsx
const user = useUser()
if (user) {
    return <User user={user} />
}

return <LoginForm />
```

That way the part were you useUser will never be rendered before the thau is loaded properly.

You solution is working fine (both of your solutions), and it's not a workaround, it's the way you work with async stuff in React - you wrap it by useEffect and do your magic. Your second approach is better as you differ the case where "Thau is loading" and "User is not logged in", while in the first one the user can be undefined just because thau is still loading (on first page render)

From this issue perspective, I think it would be good to expose `loading` and `error` from `useUser` hook as well. So you'll be able to do smth like 
```tsx
const { loading, error, user } = useUser()
```
instead of
```tsx
const { loading, error } = useAuth()
const user = useUser()
```

**Comment by mauquoic** [comment]
Yep, those were my thoughts also for changing to using the auth in the if statement, so that I can do some other logic if the loading is done and the user is simply not logged in.

But I will try to do it the "react" way. :)
Thanks a lot for the explanation!
